// Generated by gencpp from file conti_ars408_side2/config_OutputType.msg
// DO NOT EDIT!


#ifndef CONTI_ARS408_SIDE2_MESSAGE_CONFIG_OUTPUTTYPE_H
#define CONTI_ARS408_SIDE2_MESSAGE_CONFIG_OUTPUTTYPE_H

#include <ros/service_traits.h>


#include <conti_ars408_side2/config_OutputTypeRequest.h>
#include <conti_ars408_side2/config_OutputTypeResponse.h>


namespace conti_ars408_side2
{

struct config_OutputType
{

typedef config_OutputTypeRequest Request;
typedef config_OutputTypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct config_OutputType
} // namespace conti_ars408_side2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::conti_ars408_side2::config_OutputType > {
  static const char* value()
  {
    return "84258bdfadc436fc1e07d471616d0a90";
  }

  static const char* value(const ::conti_ars408_side2::config_OutputType&) { return value(); }
};

template<>
struct DataType< ::conti_ars408_side2::config_OutputType > {
  static const char* value()
  {
    return "conti_ars408_side2/config_OutputType";
  }

  static const char* value(const ::conti_ars408_side2::config_OutputType&) { return value(); }
};


// service_traits::MD5Sum< ::conti_ars408_side2::config_OutputTypeRequest> should match
// service_traits::MD5Sum< ::conti_ars408_side2::config_OutputType >
template<>
struct MD5Sum< ::conti_ars408_side2::config_OutputTypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::conti_ars408_side2::config_OutputType >::value();
  }
  static const char* value(const ::conti_ars408_side2::config_OutputTypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::conti_ars408_side2::config_OutputTypeRequest> should match
// service_traits::DataType< ::conti_ars408_side2::config_OutputType >
template<>
struct DataType< ::conti_ars408_side2::config_OutputTypeRequest>
{
  static const char* value()
  {
    return DataType< ::conti_ars408_side2::config_OutputType >::value();
  }
  static const char* value(const ::conti_ars408_side2::config_OutputTypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::conti_ars408_side2::config_OutputTypeResponse> should match
// service_traits::MD5Sum< ::conti_ars408_side2::config_OutputType >
template<>
struct MD5Sum< ::conti_ars408_side2::config_OutputTypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::conti_ars408_side2::config_OutputType >::value();
  }
  static const char* value(const ::conti_ars408_side2::config_OutputTypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::conti_ars408_side2::config_OutputTypeResponse> should match
// service_traits::DataType< ::conti_ars408_side2::config_OutputType >
template<>
struct DataType< ::conti_ars408_side2::config_OutputTypeResponse>
{
  static const char* value()
  {
    return DataType< ::conti_ars408_side2::config_OutputType >::value();
  }
  static const char* value(const ::conti_ars408_side2::config_OutputTypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTI_ARS408_SIDE2_MESSAGE_CONFIG_OUTPUTTYPE_H
