// Generated by gencpp from file conti_ars408_side1/config_SortIndex.msg
// DO NOT EDIT!


#ifndef CONTI_ARS408_SIDE1_MESSAGE_CONFIG_SORTINDEX_H
#define CONTI_ARS408_SIDE1_MESSAGE_CONFIG_SORTINDEX_H

#include <ros/service_traits.h>


#include <conti_ars408_side1/config_SortIndexRequest.h>
#include <conti_ars408_side1/config_SortIndexResponse.h>


namespace conti_ars408_side1
{

struct config_SortIndex
{

typedef config_SortIndexRequest Request;
typedef config_SortIndexResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct config_SortIndex
} // namespace conti_ars408_side1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::conti_ars408_side1::config_SortIndex > {
  static const char* value()
  {
    return "93fb6a7e64dbd2a0708217b8ad8f0eb8";
  }

  static const char* value(const ::conti_ars408_side1::config_SortIndex&) { return value(); }
};

template<>
struct DataType< ::conti_ars408_side1::config_SortIndex > {
  static const char* value()
  {
    return "conti_ars408_side1/config_SortIndex";
  }

  static const char* value(const ::conti_ars408_side1::config_SortIndex&) { return value(); }
};


// service_traits::MD5Sum< ::conti_ars408_side1::config_SortIndexRequest> should match
// service_traits::MD5Sum< ::conti_ars408_side1::config_SortIndex >
template<>
struct MD5Sum< ::conti_ars408_side1::config_SortIndexRequest>
{
  static const char* value()
  {
    return MD5Sum< ::conti_ars408_side1::config_SortIndex >::value();
  }
  static const char* value(const ::conti_ars408_side1::config_SortIndexRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::conti_ars408_side1::config_SortIndexRequest> should match
// service_traits::DataType< ::conti_ars408_side1::config_SortIndex >
template<>
struct DataType< ::conti_ars408_side1::config_SortIndexRequest>
{
  static const char* value()
  {
    return DataType< ::conti_ars408_side1::config_SortIndex >::value();
  }
  static const char* value(const ::conti_ars408_side1::config_SortIndexRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::conti_ars408_side1::config_SortIndexResponse> should match
// service_traits::MD5Sum< ::conti_ars408_side1::config_SortIndex >
template<>
struct MD5Sum< ::conti_ars408_side1::config_SortIndexResponse>
{
  static const char* value()
  {
    return MD5Sum< ::conti_ars408_side1::config_SortIndex >::value();
  }
  static const char* value(const ::conti_ars408_side1::config_SortIndexResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::conti_ars408_side1::config_SortIndexResponse> should match
// service_traits::DataType< ::conti_ars408_side1::config_SortIndex >
template<>
struct DataType< ::conti_ars408_side1::config_SortIndexResponse>
{
  static const char* value()
  {
    return DataType< ::conti_ars408_side1::config_SortIndex >::value();
  }
  static const char* value(const ::conti_ars408_side1::config_SortIndexResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTI_ARS408_SIDE1_MESSAGE_CONFIG_SORTINDEX_H
