(cl:in-package conti_ars408_side2-msg)
(cl:export '(OBJECTID-VAL
          OBJECTID
          OBJECTPOSN-VAL
          OBJECTPOSN
          OBJECTVREL-VAL
          OBJECTVREL
          OBJECTAREL-VAL
          OBJECTAREL
          OBJECTDYNPROP-VAL
          OBJECTDYNPROP
          OBJECTRCS-VAL
          OBJECTRCS
          OBJECTMEASSTATE-VAL
          OBJECTMEASSTATE
          OBJECTPROBOFEXIST-VAL
          OBJECTPROBOFEXIST
          OBJECTCLASS-VAL
          OBJECTCLASS
          OBJECTORIENTATIONANGLE-VAL
          OBJECTORIENTATIONANGLE
          OBJECTLENGTH-VAL
          OBJECTLENGTH
          OBJECTWIDTH-VAL
          OBJECTWIDTH
))