(cl:in-package conti_ars408_side2-msg)
(cl:export '(CLUSTERID-VAL
          CLUSTERID
          CLUSTERPOSN-VAL
          CLUSTERPOSN
          CLUSTERVREL-VAL
          CLUSTERVREL
          CLUSTERDYNPROP-VAL
          CLUSTERDYNPROP
          CLUSTERRCS-VAL
          CLUSTERRCS
          CLUSTERPDH0-VAL
          CLUSTERPDH0
          CLUSTERAMBIGSTATE-VAL
          CLUSTERAMBIGSTATE
          CLUSTERINVALIDSTATE-VAL
          CLUSTERINVALIDSTATE
))