// Generated by gencpp from file conti_ars408/config_SensorIDRequest.msg
// DO NOT EDIT!


#ifndef CONTI_ARS408_MESSAGE_CONFIG_SENSORIDREQUEST_H
#define CONTI_ARS408_MESSAGE_CONFIG_SENSORIDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace conti_ars408
{
template <class ContainerAllocator>
struct config_SensorIDRequest_
{
  typedef config_SensorIDRequest_<ContainerAllocator> Type;

  config_SensorIDRequest_()
    : sensorID(0)  {
    }
  config_SensorIDRequest_(const ContainerAllocator& _alloc)
    : sensorID(0)  {
  (void)_alloc;
    }



   typedef uint8_t _sensorID_type;
  _sensorID_type sensorID;





  typedef boost::shared_ptr< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> const> ConstPtr;

}; // struct config_SensorIDRequest_

typedef ::conti_ars408::config_SensorIDRequest_<std::allocator<void> > config_SensorIDRequest;

typedef boost::shared_ptr< ::conti_ars408::config_SensorIDRequest > config_SensorIDRequestPtr;
typedef boost::shared_ptr< ::conti_ars408::config_SensorIDRequest const> config_SensorIDRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::conti_ars408::config_SensorIDRequest_<ContainerAllocator1> & lhs, const ::conti_ars408::config_SensorIDRequest_<ContainerAllocator2> & rhs)
{
  return lhs.sensorID == rhs.sensorID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::conti_ars408::config_SensorIDRequest_<ContainerAllocator1> & lhs, const ::conti_ars408::config_SensorIDRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace conti_ars408

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8840ca3a2554fac83ff179bcc0342e2e";
  }

  static const char* value(const ::conti_ars408::config_SensorIDRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8840ca3a2554fac8ULL;
  static const uint64_t static_value2 = 0x3ff179bcc0342e2eULL;
};

template<class ContainerAllocator>
struct DataType< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "conti_ars408/config_SensorIDRequest";
  }

  static const char* value(const ::conti_ars408::config_SensorIDRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Sensor ID 0 – 7\n"
"\n"
"uint8 sensorID\n"
;
  }

  static const char* value(const ::conti_ars408::config_SensorIDRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensorID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct config_SensorIDRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::conti_ars408::config_SensorIDRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::conti_ars408::config_SensorIDRequest_<ContainerAllocator>& v)
  {
    s << indent << "sensorID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensorID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTI_ARS408_MESSAGE_CONFIG_SENSORIDREQUEST_H
