// Generated by gencpp from file conti_ARS408/config_RCSThresholdRequest.msg
// DO NOT EDIT!


#ifndef CONTI_ARS408_MESSAGE_CONFIG_RCSTHRESHOLDREQUEST_H
#define CONTI_ARS408_MESSAGE_CONFIG_RCSTHRESHOLDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace conti_ARS408
{
template <class ContainerAllocator>
struct config_RCSThresholdRequest_
{
  typedef config_RCSThresholdRequest_<ContainerAllocator> Type;

  config_RCSThresholdRequest_()
    : rcs_threshold(0)  {
    }
  config_RCSThresholdRequest_(const ContainerAllocator& _alloc)
    : rcs_threshold(0)  {
  (void)_alloc;
    }



   typedef uint8_t _rcs_threshold_type;
  _rcs_threshold_type rcs_threshold;





  typedef boost::shared_ptr< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct config_RCSThresholdRequest_

typedef ::conti_ARS408::config_RCSThresholdRequest_<std::allocator<void> > config_RCSThresholdRequest;

typedef boost::shared_ptr< ::conti_ARS408::config_RCSThresholdRequest > config_RCSThresholdRequestPtr;
typedef boost::shared_ptr< ::conti_ARS408::config_RCSThresholdRequest const> config_RCSThresholdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator1> & lhs, const ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.rcs_threshold == rhs.rcs_threshold;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator1> & lhs, const ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace conti_ARS408

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2395c11d5141075461a6a21a788a2778";
  }

  static const char* value(const ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2395c11d51410754ULL;
  static const uint64_t static_value2 = 0x61a6a21a788a2778ULL;
};

template<class ContainerAllocator>
struct DataType< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "conti_ARS408/config_RCSThresholdRequest";
  }

  static const char* value(const ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Sets the sensitivity of the cluster detection to\n"
"# 0x0: Standard\n"
"# 0x1: High sensitivity\n"
"\n"
"uint8 rcs_threshold\n"
;
  }

  static const char* value(const ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rcs_threshold);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct config_RCSThresholdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::conti_ARS408::config_RCSThresholdRequest_<ContainerAllocator>& v)
  {
    s << indent << "rcs_threshold: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rcs_threshold);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTI_ARS408_MESSAGE_CONFIG_RCSTHRESHOLDREQUEST_H
