# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from conti_ARS408/radar_object_info.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class radar_object_info(genpy.Message):
  _md5sum = "599a292f7c5e980e99c41704cbfb8d14"
  _type = "conti_ARS408/radar_object_info"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Object (0x60A, 0x60B, 0x60C, 0x60D)

uint8 ObjectID
geometry_msgs/PoseWithCovariance ObjectPosn
geometry_msgs/TwistWithCovariance ObjectVrel
geometry_msgs/AccelWithCovariance ObjectArel
int8 ObjectDynProp
float32 ObjectRCS
int8 ObjectMeasState
int8 ObjectProbOfExist
int8 ObjectClass
float32 ObjectOrientationAngle
float32 ObjectLength
float32 ObjectWidth
================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistWithCovariance
# This expresses velocity in free space with uncertainty.

Twist twist

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/AccelWithCovariance
# This expresses acceleration in free space with uncertainty.

Accel accel

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Accel
# This expresses acceleration in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular
"""
  __slots__ = ['ObjectID','ObjectPosn','ObjectVrel','ObjectArel','ObjectDynProp','ObjectRCS','ObjectMeasState','ObjectProbOfExist','ObjectClass','ObjectOrientationAngle','ObjectLength','ObjectWidth']
  _slot_types = ['uint8','geometry_msgs/PoseWithCovariance','geometry_msgs/TwistWithCovariance','geometry_msgs/AccelWithCovariance','int8','float32','int8','int8','int8','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ObjectID,ObjectPosn,ObjectVrel,ObjectArel,ObjectDynProp,ObjectRCS,ObjectMeasState,ObjectProbOfExist,ObjectClass,ObjectOrientationAngle,ObjectLength,ObjectWidth

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(radar_object_info, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ObjectID is None:
        self.ObjectID = 0
      if self.ObjectPosn is None:
        self.ObjectPosn = geometry_msgs.msg.PoseWithCovariance()
      if self.ObjectVrel is None:
        self.ObjectVrel = geometry_msgs.msg.TwistWithCovariance()
      if self.ObjectArel is None:
        self.ObjectArel = geometry_msgs.msg.AccelWithCovariance()
      if self.ObjectDynProp is None:
        self.ObjectDynProp = 0
      if self.ObjectRCS is None:
        self.ObjectRCS = 0.
      if self.ObjectMeasState is None:
        self.ObjectMeasState = 0
      if self.ObjectProbOfExist is None:
        self.ObjectProbOfExist = 0
      if self.ObjectClass is None:
        self.ObjectClass = 0
      if self.ObjectOrientationAngle is None:
        self.ObjectOrientationAngle = 0.
      if self.ObjectLength is None:
        self.ObjectLength = 0.
      if self.ObjectWidth is None:
        self.ObjectWidth = 0.
    else:
      self.ObjectID = 0
      self.ObjectPosn = geometry_msgs.msg.PoseWithCovariance()
      self.ObjectVrel = geometry_msgs.msg.TwistWithCovariance()
      self.ObjectArel = geometry_msgs.msg.AccelWithCovariance()
      self.ObjectDynProp = 0
      self.ObjectRCS = 0.
      self.ObjectMeasState = 0
      self.ObjectProbOfExist = 0
      self.ObjectClass = 0
      self.ObjectOrientationAngle = 0.
      self.ObjectLength = 0.
      self.ObjectWidth = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B7d().pack(_x.ObjectID, _x.ObjectPosn.pose.position.x, _x.ObjectPosn.pose.position.y, _x.ObjectPosn.pose.position.z, _x.ObjectPosn.pose.orientation.x, _x.ObjectPosn.pose.orientation.y, _x.ObjectPosn.pose.orientation.z, _x.ObjectPosn.pose.orientation.w))
      buff.write(_get_struct_36d().pack(*self.ObjectPosn.covariance))
      _x = self
      buff.write(_get_struct_6d().pack(_x.ObjectVrel.twist.linear.x, _x.ObjectVrel.twist.linear.y, _x.ObjectVrel.twist.linear.z, _x.ObjectVrel.twist.angular.x, _x.ObjectVrel.twist.angular.y, _x.ObjectVrel.twist.angular.z))
      buff.write(_get_struct_36d().pack(*self.ObjectVrel.covariance))
      _x = self
      buff.write(_get_struct_6d().pack(_x.ObjectArel.accel.linear.x, _x.ObjectArel.accel.linear.y, _x.ObjectArel.accel.linear.z, _x.ObjectArel.accel.angular.x, _x.ObjectArel.accel.angular.y, _x.ObjectArel.accel.angular.z))
      buff.write(_get_struct_36d().pack(*self.ObjectArel.covariance))
      _x = self
      buff.write(_get_struct_bf3b3f().pack(_x.ObjectDynProp, _x.ObjectRCS, _x.ObjectMeasState, _x.ObjectProbOfExist, _x.ObjectClass, _x.ObjectOrientationAngle, _x.ObjectLength, _x.ObjectWidth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ObjectPosn is None:
        self.ObjectPosn = geometry_msgs.msg.PoseWithCovariance()
      if self.ObjectVrel is None:
        self.ObjectVrel = geometry_msgs.msg.TwistWithCovariance()
      if self.ObjectArel is None:
        self.ObjectArel = geometry_msgs.msg.AccelWithCovariance()
      end = 0
      _x = self
      start = end
      end += 57
      (_x.ObjectID, _x.ObjectPosn.pose.position.x, _x.ObjectPosn.pose.position.y, _x.ObjectPosn.pose.position.z, _x.ObjectPosn.pose.orientation.x, _x.ObjectPosn.pose.orientation.y, _x.ObjectPosn.pose.orientation.z, _x.ObjectPosn.pose.orientation.w,) = _get_struct_B7d().unpack(str[start:end])
      start = end
      end += 288
      self.ObjectPosn.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.ObjectVrel.twist.linear.x, _x.ObjectVrel.twist.linear.y, _x.ObjectVrel.twist.linear.z, _x.ObjectVrel.twist.angular.x, _x.ObjectVrel.twist.angular.y, _x.ObjectVrel.twist.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.ObjectVrel.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.ObjectArel.accel.linear.x, _x.ObjectArel.accel.linear.y, _x.ObjectArel.accel.linear.z, _x.ObjectArel.accel.angular.x, _x.ObjectArel.accel.angular.y, _x.ObjectArel.accel.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.ObjectArel.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 20
      (_x.ObjectDynProp, _x.ObjectRCS, _x.ObjectMeasState, _x.ObjectProbOfExist, _x.ObjectClass, _x.ObjectOrientationAngle, _x.ObjectLength, _x.ObjectWidth,) = _get_struct_bf3b3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B7d().pack(_x.ObjectID, _x.ObjectPosn.pose.position.x, _x.ObjectPosn.pose.position.y, _x.ObjectPosn.pose.position.z, _x.ObjectPosn.pose.orientation.x, _x.ObjectPosn.pose.orientation.y, _x.ObjectPosn.pose.orientation.z, _x.ObjectPosn.pose.orientation.w))
      buff.write(self.ObjectPosn.covariance.tostring())
      _x = self
      buff.write(_get_struct_6d().pack(_x.ObjectVrel.twist.linear.x, _x.ObjectVrel.twist.linear.y, _x.ObjectVrel.twist.linear.z, _x.ObjectVrel.twist.angular.x, _x.ObjectVrel.twist.angular.y, _x.ObjectVrel.twist.angular.z))
      buff.write(self.ObjectVrel.covariance.tostring())
      _x = self
      buff.write(_get_struct_6d().pack(_x.ObjectArel.accel.linear.x, _x.ObjectArel.accel.linear.y, _x.ObjectArel.accel.linear.z, _x.ObjectArel.accel.angular.x, _x.ObjectArel.accel.angular.y, _x.ObjectArel.accel.angular.z))
      buff.write(self.ObjectArel.covariance.tostring())
      _x = self
      buff.write(_get_struct_bf3b3f().pack(_x.ObjectDynProp, _x.ObjectRCS, _x.ObjectMeasState, _x.ObjectProbOfExist, _x.ObjectClass, _x.ObjectOrientationAngle, _x.ObjectLength, _x.ObjectWidth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ObjectPosn is None:
        self.ObjectPosn = geometry_msgs.msg.PoseWithCovariance()
      if self.ObjectVrel is None:
        self.ObjectVrel = geometry_msgs.msg.TwistWithCovariance()
      if self.ObjectArel is None:
        self.ObjectArel = geometry_msgs.msg.AccelWithCovariance()
      end = 0
      _x = self
      start = end
      end += 57
      (_x.ObjectID, _x.ObjectPosn.pose.position.x, _x.ObjectPosn.pose.position.y, _x.ObjectPosn.pose.position.z, _x.ObjectPosn.pose.orientation.x, _x.ObjectPosn.pose.orientation.y, _x.ObjectPosn.pose.orientation.z, _x.ObjectPosn.pose.orientation.w,) = _get_struct_B7d().unpack(str[start:end])
      start = end
      end += 288
      self.ObjectPosn.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.ObjectVrel.twist.linear.x, _x.ObjectVrel.twist.linear.y, _x.ObjectVrel.twist.linear.z, _x.ObjectVrel.twist.angular.x, _x.ObjectVrel.twist.angular.y, _x.ObjectVrel.twist.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.ObjectVrel.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.ObjectArel.accel.linear.x, _x.ObjectArel.accel.linear.y, _x.ObjectArel.accel.linear.z, _x.ObjectArel.accel.angular.x, _x.ObjectArel.accel.angular.y, _x.ObjectArel.accel.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.ObjectArel.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 20
      (_x.ObjectDynProp, _x.ObjectRCS, _x.ObjectMeasState, _x.ObjectProbOfExist, _x.ObjectClass, _x.ObjectOrientationAngle, _x.ObjectLength, _x.ObjectWidth,) = _get_struct_bf3b3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_36d = None
def _get_struct_36d():
    global _struct_36d
    if _struct_36d is None:
        _struct_36d = struct.Struct("<36d")
    return _struct_36d
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_B7d = None
def _get_struct_B7d():
    global _struct_B7d
    if _struct_B7d is None:
        _struct_B7d = struct.Struct("<B7d")
    return _struct_B7d
_struct_bf3b3f = None
def _get_struct_bf3b3f():
    global _struct_bf3b3f
    if _struct_bf3b3f is None:
        _struct_bf3b3f = struct.Struct("<bf3b3f")
    return _struct_bf3b3f
