# Configures the transmitted radar power (Tx
# attenuation). The output RCS of cluster and objects
# will be compensated for this attenuation. Reducing
# the output power can improve detection in case of
# close range scenarios or inside rooms.

# 0x0: Standard
# 0x1: -3dB Tx gain
# 0x2: -6dB Tx gain
# 0x3: -9dB Tx gain 

uint8 radar_power
---